<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PeopleSeeder extends Seeder
{
    public function run()
    {
        DB::table('people')->insert([
            [
                'id' => 1,
                'first_name' => 'Martín Gonzalo',
                'last_name' => 'Morales Valdez',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'first_name' => 'Raúl Adalberto',
                'last_name' => 'Morelos',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3,
                'first_name' => 'Cruz Gilberto',
                'last_name' => 'García Arquieta',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4,
                'first_name' => 'Ramón',
                'last_name' => 'Cid Lucero',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'first_name' => 'Ramón Armando',
                'last_name' => 'Almodobar Sepúlveda',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 6,
                'first_name' => 'José Andrés',
                'last_name' => 'Alvarado Castro',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 7,
                'first_name' => 'Lidia Irene',
                'last_name' => 'León López',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 8,
                'first_name' => 'Gerardo',
                'last_name' => 'Calderón Ayala',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'first_name' => 'Apolinar',
                'last_name' => 'Castro Esquivel',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 10,
                'first_name' => 'Perla',
                'last_name' => 'Montaño Othón',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'first_name' => 'Hugo',
                'last_name' => 'Gavotto Nogales',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'first_name' => 'Miguel Ángel',
                'last_name' => 'Ochoa Vásquez',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'first_name' => 'José Antonio',
                'last_name' => 'Romero Montaño',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'first_name' => 'Jesús María Martín',
                'last_name' => 'Terán Gastélum',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'first_name' => 'JESÚS MARÍA MARTÍN',
                'last_name' => 'TERÁN GASTÉLUM',
                'created_at' => '2023-10-17 03:13:08',
                'updated_at' => '2023-10-17 03:13:08',
            ],
            [
                'id' => 16,
                'first_name' => 'JOSÉ CÉSAR',
                'last_name' => 'KAPLAN NAVARRO',
                'created_at' => '2023-10-17 03:28:36',
                'updated_at' => '2023-10-17 03:28:36',
            ],
            [
                'id' => 17,
                'first_name' => 'EDGARDO',
                'last_name' => 'COTA PRECIADO',
                'created_at' => '2023-10-17 03:30:09',
                'updated_at' => '2023-10-17 03:30:09',
            ],
            [
                'id' => 18,
                'first_name' => 'MARTHA ELOISA',
                'last_name' => 'SIQUEIROS CAMACHO',
                'created_at' => '2023-10-17 03:31:12',
                'updated_at' => '2023-10-17 03:31:12',
            ],
            [
                'id' => 19,
                'first_name' => 'MA. DEL ROSARIO',
                'last_name' => 'SEGURA',
                'created_at' => '2023-10-17 04:01:19',
                'updated_at' => '2023-10-17 04:01:19',
            ],
            [
                'id' => 20,
                'first_name' => 'ROSA ARMIDA',
                'last_name' => 'VALDEZ ARÁMBULA',
                'created_at' => '2023-10-17 04:02:11',
                'updated_at' => '2023-10-17 04:02:11',
            ],
            [
                'id' => 21,
                'first_name' => 'JOSÉ ANTONIO',
                'last_name' => 'NORIEGA ESCALANTE',
                'created_at' => '2023-10-19 02:27:49',
                'updated_at' => '2023-10-19 02:27:49',
            ],
            [
                'id' => 22,
                'first_name' => 'ANABEL',
                'last_name' => 'IBARRA CHAIREZ',
                'created_at' => '2023-10-19 02:28:33',
                'updated_at' => '2023-10-19 02:28:33',
            ],
            [
                'id' => 23,
                'first_name' => 'GUADALUPE MARÍA',
                'last_name' => 'ANDUAGA LUGO',
                'created_at' => '2023-10-19 03:39:24',
                'updated_at' => '2023-10-19 03:39:24',
            ],
            [
                'id' => 24,
                'first_name' => 'MARÍA CONSUELO',
                'last_name' => 'CRUZ MENDÍVIL',
                'created_at' => '2023-10-19 03:39:57',
                'updated_at' => '2023-10-19 03:39:57',
            ],
            [
                'id' => 25,
                'first_name' => 'ALMA ROCÍO',
                'last_name' => 'VALENZUELA GALAZ',
                'created_at' => '2023-10-20 03:08:48',
                'updated_at' => '2023-10-20 03:08:48',
            ],
            [
                'id' => 26,
                'first_name' => 'ÓSCAR MANUEL',
                'last_name' => 'GARCÍA SOLÍS',
                'created_at' => '2023-10-20 03:09:27',
                'updated_at' => '2023-10-20 03:09:27',
            ],
            [
                'id' => 27,
                'first_name' => 'JESÚS LEONARDO',
                'last_name' => 'MORENO GARZÓN',
                'created_at' => '2023-10-20 03:10:01',
                'updated_at' => '2023-10-20 03:10:01',
            ],
            [
                'id' => 28,
                'first_name' => 'JOSÉ ANTONIO',
                'last_name' => 'BAÑUELOS QUINTANILLA',
                'created_at' => '2023-10-20 03:10:45',
                'updated_at' => '2023-10-20 03:10:45',
            ],
            [
                'id' => 29,
                'first_name' => 'JOSÉ ALBERTO',
                'last_name' => 'SALADO RODRÍGUEZ',
                'created_at' => '2023-10-20 03:11:36',
                'updated_at' => '2023-10-20 03:11:36',
            ],
            [
                'id' => 30,
                'first_name' => 'VÍCTOR',
                'last_name' => 'PALAFOX SÁNCHEZ',
                'created_at' => '2023-10-20 03:15:23',
                'updated_at' => '2023-10-20 03:15:23',
            ],
            [
                'id' => 31,
                'first_name' => 'ANNA LYNNETH',
                'last_name' => 'JIMÉNEZ PERALTA',
                'created_at' => '2023-10-20 03:16:19',
                'updated_at' => '2023-10-20 03:16:19',
            ],
            [
                'id' => 32,
                'first_name' => 'LIZETH ALEJANDRA',
                'last_name' => 'GONZÁLEZ MARTÍNEZ',
                'created_at' => '2023-10-20 03:18:38',
                'updated_at' => '2023-10-20 03:18:38',
            ],
            [
                'id' => 33,
                'first_name' => 'LAURA ELENA',
                'last_name' => 'WOOLFOLK GALLEGO',
                'created_at' => '2023-10-20 03:19:16',
                'updated_at' => '2023-10-20 03:19:16',
            ],
            [
                'id' => 34,
                'first_name' => 'DENISSE',
                'last_name' => 'GÓMEZ BAÑUELOS',
                'created_at' => '2023-10-20 03:21:04',
                'updated_at' => '2023-10-20 03:21:04',
            ],
            [
                'id' => 35,
                'first_name' => 'LIBIA ZULEMA',
                'last_name' => 'LUGO ARMENTA',
                'created_at' => '2023-10-20 03:21:35',
                'updated_at' => '2023-10-20 03:21:35',
            ],
            [
                'id' => 36,
                'first_name' => 'BRENDA',
                'last_name' => 'SILVA SESTEAGA',
                'created_at' => '2023-10-20 03:22:22',
                'updated_at' => '2023-10-20 03:22:22',
            ],
            [
                'id' => 37,
                'first_name' => 'LUIS ENRIQUE',
                'last_name' => 'IBARRA MORALES',
                'created_at' => '2023-10-20 03:23:01',
                'updated_at' => '2023-10-20 03:23:01',
            ],
            [
                'id' => 38,
                'first_name' => 'JESÚS ADOLFO',
                'last_name' => 'DELGADILLO ZAZUETA',
                'created_at' => '2023-10-20 03:23:50',
                'updated_at' => '2023-10-20 03:23:50',
            ],
            [
                'id' => 39,
                'first_name' => 'JOSÉ ANTONIO',
                'last_name' => 'GÓMEZ VILLA',
                'created_at' => '2023-10-20 03:56:02',
                'updated_at' => '2023-10-20 03:56:02',
            ],
            [
                'id' => 40,
                'first_name' => 'PEDRO ADALBERTO',
                'last_name' => 'GONZÁLEZ LEÓN',
                'created_at' => '2023-10-20 03:56:49',
                'updated_at' => '2023-10-20 03:56:49',
            ],
            [
                'id' => 41,
                'first_name' => 'SARAÍ',
                'last_name' => 'SÁNCHEZ GÁLVEZ',
                'created_at' => '2023-10-20 03:57:17',
                'updated_at' => '2023-10-20 03:57:17',
            ],
            [
                'id' => 42,
                'first_name' => 'RUBÉN ENRIQUE',
                'last_name' => 'LEYVA DÁVILA',
                'created_at' => '2023-10-20 03:58:38',
                'updated_at' => '2023-10-20 03:58:38',
            ],
            [
                'id' => 43,
                'first_name' => 'MIRIAM CELENE',
                'last_name' => 'MARTÍNEZ LUCERO',
                'created_at' => '2023-10-20 03:59:27',
                'updated_at' => '2023-10-20 03:59:27',
            ],
            [
                'id' => 44,
                'first_name' => 'LUZ ELENA',
                'last_name' => 'MOLINA GIL',
                'created_at' => '2023-10-20 03:59:51',
                'updated_at' => '2023-10-20 03:59:51',
            ],
            [
                'id' => 45,
                'first_name' => 'LUIS ALBERTO',
                'last_name' => 'ZAZUETA CARRASCO',
                'created_at' => '2023-10-21 04:19:40',
                'updated_at' => '2023-10-21 04:19:40',
            ],
            [
                'id' => 46,
                'first_name' => 'ANA ELIZABETH',
                'last_name' => 'GÓMEZ CARDONA',
                'created_at' => '2023-10-21 04:20:39',
                'updated_at' => '2023-10-21 04:20:39',
            ],
            [
                'id' => 47,
                'first_name' => 'VÍCTOR JESÚS',
                'last_name' => 'VILLASEÑOR RUELAS',
                'created_at' => '2023-10-21 04:21:05',
                'updated_at' => '2023-10-21 04:21:05',
            ],
            [
                'id' => 48,
                'first_name' => 'RAMÓN IGNACIO',
                'last_name' => 'ROMERO NAVARRO',
                'created_at' => '2023-10-21 04:21:48',
                'updated_at' => '2023-10-21 04:21:48',
            ],
            [
                'id' => 49,
                'first_name' => 'ALMA ISABEL',
                'last_name' => 'ARIAS HURTADO',
                'created_at' => '2023-10-21 04:22:25',
                'updated_at' => '2023-10-21 04:22:25',
            ],
            [
                'id' => 50,
                'first_name' => 'CARMEN JULIA',
                'last_name' => 'LEYVA VALENZUELA',
                'created_at' => '2023-10-21 04:22:52',
                'updated_at' => '2023-10-21 04:22:52',
            ],
            [
                'id' => 51,
                'first_name' => 'MANUEL ALEJANDRO',
                'last_name' => 'VÁSQUEZ QUIJADA',
                'created_at' => '2023-10-21 04:24:42',
                'updated_at' => '2023-10-21 04:24:42',
            ],
            [
                'id' => 52,
                'first_name' => 'DAMIAN EDMUNDO',
                'last_name' => 'ESCAMILLA MONTIJO',
                'created_at' => '2023-10-21 04:25:37',
                'updated_at' => '2023-10-21 04:25:37',
            ],
            [
                'id' => 53,
                'first_name' => 'JESÚS RAMÓN',
                'last_name' => 'LÓPEZ SÁNCHEZ',
                'created_at' => '2023-10-21 04:26:01',
                'updated_at' => '2023-10-21 04:26:01',
            ],
            [
                'id' => 54,
                'first_name' => 'ANA CECILIA',
                'last_name' => 'SÁNCHEZ YAÑEZ',
                'created_at' => '2023-10-21 04:26:30',
                'updated_at' => '2023-10-21 04:26:30',
            ],
            [
                'id' => 55,
                'first_name' => 'MARÍA GUADALUPE',
                'last_name' => 'ARAIZA CARRASCO',
                'created_at' => '2023-10-21 04:26:51',
                'updated_at' => '2023-10-21 04:26:51',
            ],
            [
                'id' => 56,
                'first_name' => 'DANIEL',
                'last_name' => 'PAREDES ZEMPUAL',
                'created_at' => '2023-10-21 04:27:10',
                'updated_at' => '2023-10-21 04:27:10',
            ],
        ]);

    }
}
